# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{abstract_group}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremiah Heller"]
  s.date = %q{2010-11-04}
  s.description = %q{Provides grouping behavior to arbitrary objects in a system.}
  s.email = %q{jeremiah@inertialbit.net}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "README.textile",
     "Rakefile",
     "VERSION",
     "app/controllers/abstract_group/application_controller.rb",
     "app/controllers/application_controller.rb",
     "app/controllers/groups_controller.rb",
     "app/controllers/memberships_controller.rb",
     "app/helpers/abstract_group/application_helper.rb",
     "app/helpers/groups_helper.rb",
     "app/helpers/memberships_helper.rb",
     "app/models/group.rb",
     "app/models/groupable.rb",
     "app/models/member.rb",
     "app/models/membership.rb",
     "app/views/abstract-group-shared/_flash.html.erb",
     "app/views/abstract-group-shared/_main_menu.html.erb",
     "app/views/abstract-group-shared/_navigation.html.erb",
     "app/views/groups/_form.html.erb",
     "app/views/groups/_group_checkboxes.html.erb",
     "app/views/groups/edit.html.erb",
     "app/views/groups/index.html.erb",
     "app/views/groups/new.html.erb",
     "app/views/groups/show.html.erb",
     "app/views/layouts/application.html.erb",
     "app/views/memberships/new.html.erb",
     "config/application.rb",
     "config/blueprint_settings.yml",
     "config/boot.rb",
     "config/cucumber.yml",
     "config/environment.rb",
     "config/environments/development.rb",
     "config/environments/production.rb",
     "config/environments/test.rb",
     "config/initializers/backtrace_silencers.rb",
     "config/initializers/inflections.rb",
     "config/initializers/mime_types.rb",
     "config/initializers/secret_token.rb",
     "config/initializers/session_store.rb",
     "config/locales/en.yml",
     "config/routes.rb",
     "db/migrate/20100912182208_create_groups.rb",
     "db/migrate/20100912191020_create_memberships.rb",
     "db/schema.rb",
     "db/seeds.rb",
     "lib/abstract_group.rb",
     "lib/abstract_group/action_view.rb",
     "lib/abstract_group/asset_path.rb",
     "lib/abstract_group/engine.rb",
     "lib/generators/abstract_group/install/USAGE",
     "lib/generators/abstract_group/install/install_generator.rb",
     "lib/generators/abstract_group/install/templates/abstract_group.rake",
     "lib/tasks/blueprint.rake",
     "lib/tasks/cucumber.rake",
     "public/404.html",
     "public/422.html",
     "public/500.html",
     "public/favicon.ico",
     "public/images/rails.png",
     "public/javascripts/application.js",
     "public/javascripts/jquery-1.4.1.min.js",
     "public/javascripts/rails.js",
     "public/robots.txt",
     "public/stylesheets/abstract_group.css",
     "public/stylesheets/blueprint/icons/cross.png",
     "public/stylesheets/blueprint/icons/doc.png",
     "public/stylesheets/blueprint/icons/email.png",
     "public/stylesheets/blueprint/icons/external.png",
     "public/stylesheets/blueprint/icons/feed.png",
     "public/stylesheets/blueprint/icons/im.png",
     "public/stylesheets/blueprint/icons/key.png",
     "public/stylesheets/blueprint/icons/pdf.png",
     "public/stylesheets/blueprint/icons/tick.png",
     "public/stylesheets/blueprint/icons/visited.png",
     "public/stylesheets/blueprint/icons/xls.png",
     "public/stylesheets/blueprint/ie.css",
     "public/stylesheets/blueprint/plugins/buttons/icons/cross.png",
     "public/stylesheets/blueprint/plugins/buttons/icons/key.png",
     "public/stylesheets/blueprint/plugins/buttons/icons/tick.png",
     "public/stylesheets/blueprint/plugins/buttons/readme.txt",
     "public/stylesheets/blueprint/plugins/buttons/screen.css",
     "public/stylesheets/blueprint/plugins/fancy-type/readme.txt",
     "public/stylesheets/blueprint/plugins/fancy-type/screen.css",
     "public/stylesheets/blueprint/plugins/link-icons/icons/doc.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/email.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/external.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/feed.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/im.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/pdf.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/visited.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/xls.png",
     "public/stylesheets/blueprint/plugins/link-icons/readme.txt",
     "public/stylesheets/blueprint/plugins/link-icons/screen.css",
     "public/stylesheets/blueprint/plugins/rtl/readme.txt",
     "public/stylesheets/blueprint/plugins/rtl/screen.css",
     "public/stylesheets/blueprint/print.css",
     "public/stylesheets/blueprint/readme.txt",
     "public/stylesheets/blueprint/screen.css",
     "public/stylesheets/formtastic.css",
     "public/stylesheets/formtastic_changes.css",
     "spec/controllers/abstract_group/application_controller.rb",
     "spec/controllers/groups_controller_spec.rb",
     "spec/controllers/memberships_controller_spec.rb",
     "spec/fixtures/abstract_group_groups.yml",
     "spec/models/group_spec.rb",
     "spec/models/groupable_spec.rb",
     "spec/models/member_spec.rb",
     "spec/models/membership_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_helpers/controllers.rb",
     "spec/spec_helpers/mocks.rb",
     "spec/views/groups/index.html.erb_spec.rb",
     "spec/views/groups/new.html.erb_spec.rb",
     "spec/views/groups/show.html.erb_spec.rb"
  ]
  s.homepage = %q{http://github.com/inertialbit/abstract_group}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provides grouping behavior to arbitrary objects in a system.}
  s.test_files = [
    "spec/controllers/abstract_group/application_controller.rb",
     "spec/controllers/groups_controller_spec.rb",
     "spec/controllers/memberships_controller_spec.rb",
     "spec/models/group_spec.rb",
     "spec/models/groupable_spec.rb",
     "spec/models/member_spec.rb",
     "spec/models/membership_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_helpers/controllers.rb",
     "spec/spec_helpers/mocks.rb",
     "spec/views/groups/index.html.erb_spec.rb",
     "spec/views/groups/new.html.erb_spec.rb",
     "spec/views/groups/show.html.erb_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.1"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, ["= 2.0.1"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.1"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<formtastic>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, ["= 2.0.1"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.1"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<formtastic>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, ["= 2.0.1"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
  end
end

